version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Style
    - revive

    # Complexity
    - gocyclo

    # Security
    - gosec

  settings:
    gocyclo:
      min-complexity: 30

    staticcheck:
      checks:
        - all
        - -SA1019 # ignore deprecation warnings (fix later)

    revive:
      rules:
        - name: blank-imports
          disabled: true # allow blank imports with comments
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: package-comments
          disabled: true
        - name: range
        - name: receiver-naming
          disabled: true # allow different receiver names
        - name: time-naming
        - name: unexported-return
          disabled: true # internal packages can return unexported types
        - name: indent-error-flow
        - name: errorf

    gosec:
      excludes:
        - G104 # audit errors not checked (we use errcheck for this)
        - G115 # integer overflow (false positives on protocol types)
        - G204 # subprocess with variable (OK in scripts/)

  exclusions:
    rules:
      # Test files can have longer functions and unchecked errors
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck

      # Allow dot imports in tests
      - path: _test\.go
        linters:
          - revive
        text: "dot-imports"

      # Scripts can have subprocess calls
      - path: ^scripts/
        linters:
          - gosec

      # Allow ConfigV1 naming (widespread convention)
      - linters:
          - revive
        text: "type name will be used as config\\.ConfigV1"

formatters:
  enable:
    - gofmt
    - goimports

