version: 2
project_name: yapi

builds:
  - main: ./cmd/yapi
    binary: yapi
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

homebrew_casks:
  - name: yapi
    description: "CLI-first, offline-first, git-friendly API client for HTTP, gRPC, and TCP"
    homepage: "https://github.com/jamierpond/yapi"
    skip_upload: true
    directory: Casks
    hooks:
      post:
        install: |
          system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yapi"]
    caveats: |
      yapi is a CLI tool. After installation, run:
        yapi
      For more information: https://github.com/jamierpond/yapi
    repository:
      owner: jamierpond
      name: homebrew-yapi
      branch: main
